# Generated by Django 5.2.3 on 2025-06-19 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webdataservice', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='WDS_User',
        ),
    ]
