# Generated by Django 5.2.3 on 2025-06-19 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webdataservice', '0002_rename_user_wds_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emp_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('emp_rate', models.CharField(max_length=10)),
            ],
        ),
    ]
